version: 2.1

orbs:
  node: circleci/node@5.0.1
  browser-tools: circleci/browser-tools@1.4.0

jobs:
  run-all-tests:
    docker:
      - image: cimg/node:18.16
    steps:
      - checkout
      - browser-tools/install-chrome
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Run All Tasks
          command: npm run test:all

workflows:
  version: 2
  test-workflow:
    jobs:
      - run-all-tests
